services:
  lolo-homepage:
    build: .
    image: lolo/homepage:latest
    container_name: lolo-homepage
    restart: always
    environment:
      VIRTUAL_HOST: minghinlo.me,www.minghinlo.me
      LETSENCRYPT_HOST: minghinlo.me,www.minghinlo.me
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: 80

      DB_HOST: db
      DB_NAME: ${MARIADB_DATABASE}
      DB_USER: ${MARIADB_USER}
      DB_PASSWORD: ${MARIADB_PASSWORD}
    expose:
      - "80"
    networks:
      - nginx-proxy-net
      - homepage-db-net

  db:
    image: mariadb:12.3
    container_name: lolo-homepage-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d:ro
    command: --event-scheduler=ON
    networks:
      - homepage-db-net

volumes:
  mariadb_data:

networks:
  nginx-proxy-net:
    external: true

  homepage-db-net:
    driver: bridge
